### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by lucazandrade** [nipkownix/SH2EE-web-installer#16]
Sorry to post this here, but I really didn't know where to contact about this...

Hi, I'm BIG BOSS (Lucaz Andrade), I'm part of the team that produced a translation for Silent Hill 2: Enhanced Edition.
Recently my colleague "OAleex" asked you for help here on github, because of the menu graphics.
And you kindly helped us in this endeavor, we are very grateful.
I come to inform you that we have finished the translation, into Brazilian Portuguese, I understand that other teams have already made translations into our language, but they have been heavily criticized for the lack of fidelity in certain aspects, in addition to spelling errors, we are not belittling anyone's work, we are not misunderstand,
I'm just reporting what many users in my country say, including Streamers...
In order to create a better translation for our language, and without such errors, we made this project,
for Brazilian Silent Hill fans to have something more faithful to the original work.
The translation was recently finished, and 100% tested, including all endings, plus all interaction texts, and revised secrets...
In addition, it was designed for both nostalgic players, who play in 4:3 and younger players, who play in 16:9.

We would gladly offer her to the Enhanced Edition project, we don't want credits, it's not necessary,
unless the Enhanced Edition wants to give it to us, but it really has no need, after all, that's not our purpose,
but rather, provide the ultimate experience for Brazilian fans...

Why are we offering?

Well, as I said, so that Brazilian fans have a more faithful experience.
And maybe, you including directly in the project, the access to the fans, it becomes more direct,
That's if you want...

The translation was done using the "English" language as a base.
But it was placed in the archives of the "Italian" language, since unlike "Spanish", it doesn't look so much like our language.
It has not yet been made available anywhere, nor has it been released.

Conclusions:

As I said, giving credit to us is not necessary, our objective, as has been said before, is not this!
And yes, to see a good translation in our language, made with affection from fan to fan, in an extremely detailed way.
With respected grammatical rules, and an interpretation that does not deviate from the narrative and objective intentions of the texts.

If you accept our proposal, just show us how to send the files to you...

I really appreciate the help of "Polymega" and: Copyright © 2019 Gianluigi "Infrid" Cusimano, Víctor "IlDucci" González

Who created the incredible tool for translating this incredible work by Team Silent.

Hope I didn't bother you, and thank you very much for your attention!

**Comment by nipkownix** [comment]
Hmm, you're talking about a translation for the actual game, right? Not the installer? This repo is for the installer, so that got me a bit confused.

Guess I should tag @Polymega

**Comment by lucazandrade** [comment]
> Hmm, you're talking about a translation for the actual game, right? Not the installer? This repo is for the installer, so that got me a bit confused.
> 
> Guess I should tag @Polymega

I'm talking about the whole game, sorry I was trying to talk to him, I'm not used to Github... forgive me...

**Comment by Polymega** [comment]
Hi @lucazandrade ,

For the project, I am happy to include whichever version of a PTBR translation pack that is most accepted for use by the Brazilian community. 

The only thing is that RobertoSAG reached out to me quite a while ago asking us to use his PTBR pack (before I met you and OAleex). I feel the right thing to do in this situation is to speak with him about it. I think it would be rude not to do this.

However, I would prefer not to be the middleman in this situation, especially because I do not understand the language or the nuances each translation pack has to offer. Can we approach a discussion with RobertoSAG in order to come to a mutual understanding?

**Comment by lucazandrade** [comment]
> Hi @lucazandrade ,
> 
> For the project, I am happy to include whichever version of a PTBR translation pack that is most accepted for use by the Brazilian community.
> 
> The only thing is that RobertoSAG reached out to me quite a while ago asking us to use his PTBR pack (before I met you and OAleex). I feel the right thing to do in this situation is to speak with him about it. I think it would be rude not to do this.
> 
> However, I would prefer not to be the middleman in this situation, especially because I do not understand the language or the nuances each translation pack has to offer. Can we approach a discussion with RobertoSAG in order to come to a mutual understanding?

Yes, of course, for sure!

**Comment by Polymega** [comment]
Thanks. Are you okay if I have you reach out to RobertoSAG with this discussion?

**Comment by lucazandrade** [comment]
> Thanks. Are you okay if I have you reach out to RobertoSAG with this discussion?

Yes.

**Comment by Polymega** [comment]
Great. Thanks again. Can you send me your completed translation pack whenever you're ready?

There are a few special requirements for translation packs with our project. Have you adjusted the following?:

1. [Have you kept translations within a 4:3 boundary?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.bgoye4s4iq8a)
2. A few lines in the game, such as "I'll wait at BAR Neely's" and "The door what wakes in darkness, opening into nightmares" should be blue, not white. [Have these colors been fixed?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.1d337z371evw)
3. Nearly all of the save location names have their colors changed for the save menu, to make their coloring more consistent. [Have you changed the colors to be compliant?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)
4. There are character limitations for a few strings in the pause menu. [Are you within these character limitations?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)

**Comment by lucazandrade** [comment]
> Great. Thanks again. Can you send me your completed translation pack whenever you're ready?
> 
> There are a few special requirements for translation packs with our project. Have you adjusted the following?:
> 
> 1. [Have you kept translations within a 4:3 boundary?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.bgoye4s4iq8a)
> 2. A few lines in the game, such as "I'll wait at BAR Neely's" and "The door what wakes in darkness, opening into nightmares" should be blue, not white. [Have these colors been fixed?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.1d337z371evw)
> 3. Nearly all of the save location names have their colors changed for the save menu, to make their coloring more consistent. [Have you changed the colors to be compliant?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.ndiyy5lr2js)
> 4. There are character limitations for a few strings in the pause menu. [Are you within these character limitations?](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#heading=h.fns41fbpz7b8)

Yes, of course,
Where can I send?

**Comment by Polymega** [comment]
You can send as an attachment here, if you'd like. I'll look over the files and get them packaged in a way that is ready for our next major project update. Thanks!

**Comment by lucazandrade** [comment]
> You can send as an attachment here, if you'd like. I'll look over the files and get them packaged in a way that is ready for our next major project update. Thanks!

BIG BOSS (Lucaz Andrade) & OAleex

 It is with great pleasure and satisfaction that we offer you one of the most detailed translation projects we have ever done.
The translation has been tested over 28 times to ensure maximum originality
and matching EE design requirements.
It took months of work, but we are proud of it.
This translation will not be available on any site for download, being
exclusive to the EE project, if so you, project developers, accept it
as part of it.
The intention is only to favor the Brazilian fans, and not to earn credit, we only started this project,
due to many requests from the SH2 Brasil community, fans who wanted an error-free translation of
spelling, respecting originality and according to the requirements of the EE project - and why
many of them have seen other works of ours and trust us.
Sorry for trying to communicate here, and I'll be available for any support
if necessary.
Thank you very much for your attention, and for this wonderful project that is EE.
Thanks!
Attach the files: 
[SH2EE - Brazilian Portuguese Translation.zip](https://github.com/nipkownix/SH2EE-web-installer/files/9758619/SH2EE.-.Brazilian.Portuguese.Translation.zip)

**Comment by Polymega** [comment]
@lucazandrade and @OAleex
Thank you both very much for your hard work. We here at the Enhanced Edition team thank you and so does the Brazilian Portuguese community. I have looked over your work, checking key spots to [ensure compliancy with our project's text requirements](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#), and everything looks great. 

When we release our next project update, it will include an entirely revamped approach in how we handle fan translation packs. Currently, translation packs are overwritten if the user ever updates the Enhanced Edition Essential Files package. We don't want this to happen, so what we're doing is housing translation packs in an entirely new directory that will never be touched/affected when a user updates project packages.

To prepare your translation pack for this adjustment to the project, I have moved some files around so that it will be ready to go whenever we release the next project update. I will happily release your translation pack on the project site when this happens, to coincide with the project's update. In the meantime, please download your translation pack below with these updates:

[Brazilian-Portuguese.zip](https://github.com/nipkownix/SH2EE-web-installer/files/9760576/Brazilian-Portuguese.zip)

I have not modified any contents of the files; I just moved/renamed the d3d8.res file to `\etc\resource\r_menu_i.res` and changed the main folder from `sh2e` to `lang`.

This is what your translation pack will look like on the website, once the next project update goes live:

https://user-images.githubusercontent.com/27395260/195224814-257a127f-e846-470d-931e-203938eac6d9.mp4

Both of your names will be credited on the download for the translation pack. Would you like me to include a link in your names on the site? If so, please let me know which links you'd like me to use for each of your names.

Thank you very much again for allowing us to host your translation pack. I am thrilled we all are finally able to bring more languages to SH2/our project in this way.

**Comment by lucazandrade** [comment]
> @lucazandrade and @OAleex Thank you both very much for your hard work. We here at the Enhanced Edition team thank you and so does the Brazilian Portuguese community. I have looked over your work, checking key spots to [ensure compliancy with our project's text requirements](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#), and everything looks great.
> 
> When we release our next project update, it will include an entirely revamped approach in how we handle fan translation packs. Currently, translation packs are overwritten if the user ever updates the Enhanced Edition Essential Files package. We don't want this to happen, so what we're doing is housing translation packs in an entirely new directory that will never be touched/affected when a user updates project packages.
> 
> To prepare your translation pack for this adjustment to the project, I have moved some files around so that it will be ready to go whenever we release the next project update. I will happily release your translation pack on the project site when this happens, to coincide with the project's update. In the meantime, please download your translation pack below with these updates:
> 
> [Brazilian-Portuguese.zip](https://github.com/nipkownix/SH2EE-web-installer/files/9760576/Brazilian-Portuguese.zip)
> 
> I have not modified any contents of the files; I just moved/renamed the d3d8.res file to `\etc\resource\r_menu_i.res` and changed the main folder from `sh2e` to `lang`.
> 
> This is what your translation pack will look like on the website, once the next project update goes live:
> 
>  2022-10-11.20-56-56.mp4 
> Both of your names will be credited on the download for the translation pack. Would you like me to include a link in your names on the site? If so, please let me know which links you'd like me to use for each of your names.
> 
> Thank you very much again for allowing us to host your translation pack. I am thrilled we all are finally able to bring more languages to SH2/our project in this way.

We appreciate your attention, thank you very much, it was really hard work, but in the end, it is worth knowing that everything was very well done, as well as your project, thank you!

**Comment by Polymega** [comment]
It's our pleasure to finally be able to do this. ❤️  If you'd like me to put a link in your name (and OAleex's name) for the credits, please let me know which link you'd like me to use for each of your names.

**Comment by ghost** [comment]
> It's our pleasure to finally be able to do this. ❤️  If you'd like me to put a link in your name (and OAleex's name) for the credits, please let me know which link you'd like me to use for each of your names.

First of all, thank you very much for making this location of ours accessible, for our mother tongue, honestly I have no comments, I just have to thank you.

I'll leave here the link to my YouTube channel, feel free.
https://youtube.com/channel/UCYZhGk77FrWsgUIirwKu1tg

**Comment by lucazandrade** [comment]
> It's our pleasure to finally be able to do this. ❤️ If you'd like me to put a link in your name (and OAleex's name) for the credits, please let me know which link you'd like me to use for each of your names.

The credits weren't necessary, but I really appreciate that too, the only network I have is my Discord, my tag is: BIG BOSS#7105

**Comment by lucazandrade** [comment]
> > @lucazandrade and @OAleex Thank you both very much for your hard work. We here at the Enhanced Edition team thank you and so does the Brazilian Portuguese community. I have looked over your work, checking key spots to [ensure compliancy with our project's text requirements](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit#), and everything looks great.
> > When we release our next project update, it will include an entirely revamped approach in how we handle fan translation packs. Currently, translation packs are overwritten if the user ever updates the Enhanced Edition Essential Files package. We don't want this to happen, so what we're doing is housing translation packs in an entirely new directory that will never be touched/affected when a user updates project packages.
> > To prepare your translation pack for this adjustment to the project, I have moved some files around so that it will be ready to go whenever we release the next project update. I will happily release your translation pack on the project site when this happens, to coincide with the project's update. In the meantime, please download your translation pack below with these updates:
> > [Brazilian-Portuguese.zip](https://github.com/nipkownix/SH2EE-web-installer/files/9760576/Brazilian-Portuguese.zip)
> > I have not modified any contents of the files; I just moved/renamed the d3d8.res file to `\etc\resource\r_menu_i.res` and changed the main folder from `sh2e` to `lang`.
> > This is what your translation pack will look like on the website, once the next project update goes live:
> > 2022-10-11.20-56-56.mp4
> > Both of your names will be credited on the download for the translation pack. Would you like me to include a link in your names on the site? If so, please let me know which links you'd like me to use for each of your names.
> > Thank you very much again for allowing us to host your translation pack. I am thrilled we all are finally able to bring more languages to SH2/our project in this way.
> 
> We appreciate your attention, thank you very much, it was really hard work, but in the end, it is worth knowing that everything was very well done, as well as your project, thank you!

Sorry, but I could make a small update in the translation files, it's a simple thing, it's not a mistake, I just thought about the possibility of someone doing one for European Portuguese, and in the translation it only has "Portuguese", I think it's more ideal " Brazilian Portuguese", the attached files are below (I put everything in the folders, to make it easier for you, just copy and paste, it's the way you rearranged it, I recommend replacing everything at once, or use the file below lol), sorry for that, I hadn't thought of this possibility, and again, thank you very much.

[Brazilian-Portuguese.zip](https://github.com/nipkownix/SH2EE-web-installer/files/9762492/Brazilian-Portuguese.zip)

**Comment by Polymega** [comment]
Done! If you're okay to do so, feel free to close this ticket out. (It can always be commented on while closed or re-opened.) If you ever need to reach out to me through email, you can send me a message through here for us to have each other's email: http://ratio.townofsilenthill.com/about/#contactme

**Comment by lucazandrade** [comment]
> Done! If you're okay to do so, feel free to close this ticket out. (It can always be commented on while closed or re-opened.) If you ever need to reach out to me through email, you can send me a message through here for us to have each other's email: http://ratio.townofsilenthill.com/about/#contactme
Thank you, wonderful, I will do that.
