### ISSUE TITLE
Future Setup Tool Adjustments

### ISSUE THREAD

**Issue by Polymega** [nipkownix/SH2EE-web-installer#17]
Hi nipkow,

I figured it might be better/easier for us to keep track of these requests if an official ticket is made. Below is a copy + paste of what I've previously emailed you about, but also includes a new feature request. Thank you.

----------

### ✔️ Remove "lang" folder if user uninstalls

For the launcher, can you please add a `lang` folder (which will be located in the game's main directory) to be removed if the user uninstalls the project? 

The `lang` folder will be introduced as part of our next project update. This folder will house fan translation packs. When in this folder, there's no risk of them ever being removed/overwritten due to a project update.

----------

### ✔️ Change XInput Plus (package name) to Xidi
We're likely going to change the use of XInput Plus to [Xidi](https://github.com/samuelgr/Xidi%5D). If this happens, we'd need to change the name of this package in the installer from "XInput Plus" to "Xidi".

Additionally, we'd need to run a check where, if Xidi is installed or updated, it will _first_ look for and delete the following (XInput Plus) files _before_ extracting the Xidi files:
```
Dinput.dll
Dinput8.dll
XInput1_3.dll
XInput1_4.dll
XInputPlus.ini
```
^ Basically, have this behave the same as what you did when updating the SH2E module (where it looks for certain files to delete first before extracting the new SH2E module files).

This Xidi change isn't set in stone yet, but wanted to make you aware. [You can see our discussions on Xidi here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/620)

---------------

### ✔️ Include a new package: "Credits"
This package will simply be the `credits.bik` (PC credits) video placed into its own package. More and more wonderful people are joining our team and we, of course, want to make sure they're credited in the project/game through the end credits video. 

However, each time I update the credits video to include new names, a user must redownload the **entire** FMV pack. That's not ideal. So let's create a whole new package for the installer to grab/download called "Credits". **This would be a required package to download on an initial install, the same as the SH2E module and Enhanced Executable.**

**Comment by nipkownix** [comment]
> Remove "lang" folder if user uninstalls

Done.

> Change XInput Plus (package name) to Xidi

Hmm, based on the discussions, it seems like we are indeed moving to Xidi, then? If so, should I make the changes now?

> Include a new package: "Credits"

Should be a simple change, but we are going to need a description for the new package.

**Comment by Polymega** [comment]
> Hmm, based on the discussions, it seems like we are indeed moving to Xidi, then? If so, should I make the changes now?

The change should happen. [We're waiting to see what its creator has to say about DirectInput controllers not being detected while Xidi is in use.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/620#issuecomment-1295977731) However, from what he said, DirectInput controllers should work if plugged in alongside Xidi, so we should be good to go once this issue is resolved.

> Should be a simple change, but we are going to need a description for the new package.

_**Acknowledging and showing love to those who have made this project possible! This is the Silent Hill 2 PC credits video that includes Silent Hill 2: Enhanced Edition credits. (This is a supplementary video, separate from the original game credits video.)**_

Thanks, nipkow!

**Comment by Polymega** [comment]
Just now slightly edited that description so people don't get confused and think we're overwriting the original game credits video.

**Comment by nipkownix** [comment]
> credits

Thanks! Done. Looks like this:
![image](https://user-images.githubusercontent.com/33870163/199090708-d710092d-dab8-45a5-972b-f6d3d53a1a6d.png)

I guess we should ping translators here too, to get localized versions of the description?

Edit: Made the changes to use Xidi instead:
![image](https://user-images.githubusercontent.com/33870163/199103287-405f20b4-c0de-4d28-b40b-0bd8da355f82.png)

Also uploaded a test build to our server, so you can test the logic for deletion of the old files (but everything should be good.)

By the way, should we change anything else in the file list for the uninstallation process due to moving to Xidi?

**Comment by Polymega** [comment]
> I guess we should ping translators here too, to get localized versions of the description?

Yep! 

@Bruno3589 @IlDucci @nipkownix 
May I ask you to translate the lines directly below?

Acknowledging and showing love to those who have made this project possible! This is the Silent Hill 2 PC credits video that includes Silent Hill 2: Enhanced Edition credits. (This is a supplementary video, separate from the original game credits video.)

> Also uploaded a test build to our server, so you can test the logic for deletion of the old files (but everything should be good.)

Thank you very much!

> By the way, should we change anything else in the file list for the uninstallation process due to moving to Xidi?

Good point: Xidi will use the following files:

```
dinput8.dll
Xidi.ini
```

^ These files _might_ change, depending on what Samuel (Xidi's creator) best suggests for use with the project.

**Comment by IlDucci** [comment]
> May I ask you to translate the lines directly below?

Sure thing!

**_¡El reconocimiento y muestra de cariño hacia todos los que han hecho posible este proyecto! Este es el vídeo con los créditos de la versión de PC de Silent Hill 2, que ahora también incluye los créditos de Silent Hill 2: Enhanced Edition (este es un vídeo suplementario y diferente a los créditos originales del juego)._**

**Comment by Bruno3589** [comment]
Hi! Sorry for the delay but it's been a busy week.
Here it is:

> Un riconoscimento e una dimostrazione d'affetto a tutti coloro che hanno reso possibile questo progetto! Questo è il video dei titoli di coda della versione PC di Silent Hill 2 che include i crediti di Silent Hill 2: Enhanced Edition. (si tratta di un video aggiuntivo, indipendente dai titoli di coda originali del gioco).

**Comment by Polymega** [comment]
Thanks IlDucci and Bruno!!

I've asked a friend to translate this in Japanese. Once translated, I'll share it here.

**Comment by Polymega** [comment]
Japanese translated:

このプロジェクトの達成に御尽力くださった方々に、心よりお礼を申し上げます。これは、サイレントヒル・エンハンスト・エディションのクレジットを含む、サイレントヒル2　ＰＣビデオのクレジットビデオです。（これは、オリジナルのゲーム・クレジットビデオとは別の補足ビデオです。）

**Comment by Polymega** [comment]
Hi nipkow!

It's been a moment. I'm trying to refresh my memory on where we left off with this. If memory serves:

------------

### ✔️ Include Spanish/Italian/Japanese translations for the new "Credits" installation package

These translations can be found right above this post.

-------------

### ✔️ Check and remove certain files on a _new install_ as well

You have checks to do this when updating project files, but this should also be done for a fresh install, in case someone previously manually downloaded our project files. [See comments here.](https://github.com/nipkownix/SH2EE-web-installer/commit/8d2ddf182ac2f5d4bb3b84b886e7fba3cd524150#commitcomment-89722716)

It looks like the conditional check needs to be changed to "if new install OR in maintenance mode" for these parts:

- https://github.com/nipkownix/SH2EE-web-installer/blob/master/wpExtract.iss#L93
- https://github.com/nipkownix/SH2EE-web-installer/blob/master/wpExtract.iss#L110

-------------------

### ✔️ Add a _new_ check for removing existing files

Gemini is working on an exciting new feature for the project: Replacement of the FMV's Bink files with MP4 video files. This will allow video files at half the file size without sacrificing quality. To coincide with this, can we please also add the following?

- If new install OR maintenance mode and user downloads **FMV Enhancement Pack**:
   - Look for and delete these files _before_ extracting the contents of the FMV Enhancement Pack:
```
// Try and delete old Bink FMV files
\sh2e\movie\credits.bik
\sh2e\movie\deai.bik
\sh2e\movie\end.bik
\sh2e\movie\end_dog.bik
\sh2e\movie\end_wish.bik
\sh2e\movie\flash.bik
\sh2e\movie\gero.bik
\sh2e\movie\hakaba.bik
\sh2e\movie\hei.bik
\sh2e\movie\knife.bik
\sh2e\movie\korosu_a.bik
\sh2e\movie\korosu_b.bik
\sh2e\movie\murder.bik
\sh2e\movie\open.bik
\sh2e\movie\rouya.bik
\sh2e\movie\saikai.bik
\sh2e\movie\sh2e3.bik
\sh2e\movie\sh3e3.bik
\sh2e\movie\sh3tgs.bik
\sh2e\movie\toilet.bik
\sh2e\movie\water.bik
```

- If new install OR maintenance mode and user downloads **Credits Pack**:
   - Look for and delete these files _before_ extracting the contents of the Credits Pack:
```
// Try and delete old Bink FMV files
\sh2e\movie\credits.bik
```

--------------

I think that was everything, but it's been a moment so I might have forgotten something.

Thank you!

**Comment by nipkownix** [comment]
Ah sorry, I've been a bit busy with [re4_tweaks](https://github.com/nipkownix/re4_tweaks) lately, trying to get a new release out.
I'll implement the changes you mentioned soon. Sorry about the delay!

Edit: Changes implemented and test build uploaded to our ftp as usual. Let me know if everything is working as expected.

**Comment by Polymega** [comment]
Thank you, sir! I'll try and get to testing the test build soon. Happy Holidays to you!

**Comment by nipkownix** [comment]
No problem! And happy Holidays to you too, friend!

**Comment by Polymega** [comment]
Ran some tests and only encountered one oddity: https://github.com/nipkownix/SH2EE-web-installer/blob/master/wpExtract.iss#L91-L105

```
      // Custom actions for sh2emodule before extraction
      if WebCompsArray[i].id = 'sh2emodule' then
      begin
        if FileExists(WizardDirValue + '\d3d8.ini') then
        begin 
          // Backup current .ini settings into an array
          CurIniArray := IniToSettingsArray(WizardDirValue + '\d3d8.ini');
          if {#DEBUG} then Log('# Backed up d3d8.ini settings');
          // Try to delete old/unused sh2ee project files
          DeleteFile(WizardDirValue + '\d3d8.res');
          DeleteFile(WizardDirValue + '\d3d8.dat');
          DeleteFile(WizardDirValue + '\D3DCompiler_43.dll');
          DeleteFile(WizardDirValue + '\D3DX9_43.dll');
        end;
      end;
```

It looks like the tool won't delete those file _unless_ a `d3d8.ini` already exists. I believe the hierarchy would just need to be changed to something like this?

```
      // Custom actions for sh2emodule before extraction
      if WebCompsArray[i].id = 'sh2emodule' then
      begin
        if FileExists(WizardDirValue + '\d3d8.ini') then
        begin 
          // Backup current .ini settings into an array
          CurIniArray := IniToSettingsArray(WizardDirValue + '\d3d8.ini');
          if {#DEBUG} then Log('# Backed up d3d8.ini settings');
        end;
          // Try to delete old/unused sh2ee project files
          DeleteFile(WizardDirValue + '\d3d8.res');
          DeleteFile(WizardDirValue + '\d3d8.dat');
          DeleteFile(WizardDirValue + '\D3DCompiler_43.dll');
          DeleteFile(WizardDirValue + '\D3DX9_43.dll');
      end;
```

**Comment by nipkownix** [comment]
Huh, is there a scenario where these files exist, but ``d3d8.ini`` doesn't? I was under the impression that never happens 🤔

**Comment by Polymega** [comment]
You're right; it probably never would happen. It's your call on changing that or not. 👍 

One other thing, if you don't mind: Please add `sh2e\movie\ending.bik` [to this list](https://github.com/nipkownix/SH2EE-web-installer/blob/master/wpExtract.iss#L121-L142) and that should cover everything. After that, I think we're good for a new public build at your discretion.

Thanks again, nipkow!

**Comment by Polymega** [comment]
Actually, hold off on making a new public build at this time, please. I forgot that Elisha may want to change the URL for the CSV file. I'll talk with him again about this soon.

**Comment by nipkownix** [comment]
> One other thing, if you don't mind: Please add sh2e\movie\ending.bik [to this list](https://github.com/nipkownix/SH2EE-web-installer/blob/master/wpExtract.iss#L121-L142) and that should cover everything.

Sure, done.

> Thanks again, nipkow!

No problem!

> Actually, hold off on making a new public build at this time, please. I forgot that Elisha may want to change the URL for the CSV file. I'll talk with him again about this soon.

Oh, changing the URL will break every public release of the Setup Tool. It needs that to even update itself. Unless you're planning to keep the old URL alive for legacy versions of the tool? I haven't seen any discussion about changing the URL, so I wasn't aware of any potential problems with it.

**Comment by Polymega** [comment]
Yes, so if we were to change this, a CSV would always be located at the current URL for legacy purposes.

Elisha and I were discussing this via email a few months ago, so my memory on all of this is fuzzy at the moment. We were discussing this back when I was having all those issues with my hosting provider. 

The problem was that I _was totally locked out of my server_ during that time, so I couldn't even go in to update the CSV file to redirect traffic to a temporary hosting solution (like the Amazon AWS S3 solution to allow people to download the project files while I was sorting out my hosting troubles). 

So the idea is to host the CSV either within your repo here or within Elisha's SH2E repo. That way, if a situation ever arises again with my hosting provider like what previously happened, we're not locked out of updating the CSV. Let me touch base with Elisha first, though, to catch myself back up to speed on this plan.
