### ISSUE TITLE
Suggestion: Allowing Maintenance Mode to be run without an internet connection

### ISSUE THREAD

**Issue by MarioTainaka** [nipkownix/SH2EE-web-installer#18]
I know this is a very weird edge case... but please allow Maintenance Mode to be run when there's no internet connection active. I get that the CSV file needs to be downloaded and checked but if  for some reason someone wants to un-install and do a re-install without internet you're just stuck. because no closes the installer. Also maybe add an option to run the repair mode using backed up files.

![image](https://user-images.githubusercontent.com/32436919/221387823-11163911-978a-47f0-abc6-569c4a371a78.png)

**Comment by Polymega** [comment]
> but if for some reason someone wants to un-install and do a re-install without internet you're just stuck.

This is a good point. I'll ask nipkow about this to see if we can perform the online CSV check while in maintenance mode _only_ if the user selects "Install or Repair Packages" or "Update Packages."

Do note that if the user selects "Install and backup enhancement packages" during the initial installation, the folder where they downloaded the packages to will act as an "offline" installer. This folder would also contain a local CSV file that the offline installer uses; no internet connection required. But an internet connection would obviously be needed to check for project updates or install packages they never installed in the first place.

**Comment by nipkownix** [comment]
Should be working as requested in the new release.
