### ISSUE TITLE
Translated Lines Needed - Multiple Languages

### ISSUE THREAD

**Issue by Polymega** [nipkownix/SH2EE-web-installer#19]
✔️ @mercury501  (Italian)
✔️ @lucazandrade (PT-BR)
✔️ @IlDucci (Spanish)
✔️ @lullulabydreams  (Japanese)

Translator friends, may we ask you to translate a few more text strings for the Setup Tool? Information below:

-----------------
> Downloads the enhancement packages to a temporary Windows AppData folder for project installation.

- This is an edit to a pre-existing string where we added the words "Windows AppData" into the string. See here for example: https://github.com/nipkownix/SH2EE-web-installer/commit/e5798fbe988b81cff6e20c30a10e48e4913120b8#diff-6e56001e33bc6affecacdc4295020860cd2d9bf63bc3787421fd81e18ed0516aR42

-----------------
> Feature unavailable. Cannot contact server. Please try again later.

- This is an all-new text string. See here for an example: https://github.com/nipkownix/SH2EE-web-installer/commit/a53e3ef9c1a777e700f1ad3f2dde942e64c0f216

-----------------

> Error: Checksum mismatch`%n%n`File '`%1`' is corrupted.`%n%n`Do you wish to skip the installation of this component and move to the next one?`%n%n`NOTE: You can try installing this component again after the installation has been completed by opening the Setup Tool (SH2EEsetup.exe) in the game's folder, and choosing "Install or Repair Packages". It is strongly recommended you do so in order to fully experience Silent Hill 2: Enhanced Edition.

- This is an all-new text string. See here for an example: https://github.com/nipkownix/SH2EE-web-installer/commit/4cb669fd3d27df9aa7d58d5943c05820bc095ee0#diff-6e56001e33bc6affecacdc4295020860cd2d9bf63bc3787421fd81e18ed0516aR111
- A similar, pre-existing string already exists for this line as `ChecksumMismatchMaintenance`. You can use this pre-existing string already made in your language as a base/reference when translating this new string. See here: https://github.com/nipkownix/SH2EE-web-installer/blob/master/languages/English.iss#L113

-------------------

Thank you all for your help with this!

**Comment by Polymega** [comment]
(Updated post to include one other piece of translation needed.)

**Comment by Polymega** [comment]
@nipkownix 
A fan pointed out that there is a typo here. It should say "Português" instead of "Portugês".

![image](https://user-images.githubusercontent.com/27395260/221437655-e8f4d719-20fe-4976-919c-4910d2d6f1bf.png)

**Comment by lucazandrade** [comment]
> @nipkownix A fan pointed out that there is a typo here. It should say "Português" instead of "Portugês".
> 
> ![image](https://user-images.githubusercontent.com/27395260/221437655-e8f4d719-20fe-4976-919c-4910d2d6f1bf.png)

Well, if and allow me to get into the subject... there are some spelling errors in Portuguese in the Setup, so I offered myself for a review, I thought that whoever had made these texts was not a native speaker, due to the mistakes...

**Comment by Polymega** [comment]
He's from Brazil and a native speaker, but he has a lot of things going on between working on this Setup Tool, [re4_tweaks](https://github.com/nipkownix/re4_tweaks)/[RE4HD project](https://www.re4hd.com/), and his real life job. It's totally understandable that some typos may happen! I know I make a lot of typos myself. 😅

**Comment by nipkownix** [comment]
> A fan pointed out that there is a typo here. It should say "Português" instead of "Portugês".

Huh, never noticed this one. Thanks for bringing this up.

>I thought that whoever had made these texts was not a native speaker, due to the mistakes...

I expected some typos here and there since I never had any QC done in the translation. Let me know of any other mistakes you find.

**Comment by lucazandrade** [comment]
> He's from Brazil and a native speaker, but he has a lot of things going on between working on this Setup Tool, [re4_tweaks](https://github.com/nipkownix/re4_tweaks)/[RE4HD project](https://www.re4hd.com/), and his real life job. It's totally understandable that some typos may happen! I know I make a lot of typos myself. 😅

I imagine, sorry, because I work with portuguese language, I get a little paranoid! 😅

**Comment by IlDucci** [comment]
**Spanish (Spain) updates:**

> **Downloads the enhancement packages to a temporary Windows AppData folder for project installation.**

_Descarga los paquetes de mejora a una carpeta temporal dentro de la carpeta AppData de Windows e instala el proyecto._

> **Feature unavailable. Cannot contact server. Please try again later.**

_Componente no disponible: no se pudo contactar con el servidor. Vuelve a intentarlo más tarde._

> **Error: Checksum `mismatch%n%nFile '%1'` is corrupted.`%n%n`Do you wish to skip the installation of this component and move to the next one?`%n%n`NOTE: You can try installing this component again after the installation has been completed by opening the Setup Tool (SH2EEsetup.exe) in the game's folder, and choosing "Install or Repair Packages". It is strongly recommended you do so in order to fully experience Silent Hill 2: Enhanced Edition.**

_Error: suma de comprobación incorrecta%n%nEl archivo «%1» está dañado.%n%n¿Deseas saltarte la instalación de este componente y pasar al siguiente?%n%nNOTA: podrás volver a intentar instalar este componente de nuevo una vez haya terminado la instalación, ejecutando la herramienta de configuración (SH2EEsetup.exe) que se encuentra en la carpeta del juego y después, dentro de la misma, selecciona «Instalar o reparar paquetes». Se recomienda encarecidamente que sigas estos pasos para poder disfrutar de la experiencia completa que ofrece Silent Hill 2: Enhanced Edition._

> **Error: Checksum `mismatch%n%nFile '%1'` is corrupted.`%n%n`The installation of this component will be skipped. Please try again, and if the issue persists, report it to the developers.**

_Error: suma de comprobación incorrecta%n%nEl archivo «%1» está dañado.%n%nSe omitirá la instalación de este componente. Vuelve a intentarlo y, si el problema persiste, avisa a los desarrolladores._

**Comment by Polymega** [comment]
Depending on its translation length, the "Feature unavailable. Cannot contact server. Please try again later." string might break down and create four lines under a package name (too many lines).

![image](https://user-images.githubusercontent.com/27395260/221449379-52623b1f-811c-4e36-a426-24aec6476240.png)

If this ultimately happens, it might be good to only show the error string:

![image](https://user-images.githubusercontent.com/27395260/221449401-7ed5413c-4ad4-400e-9e03-328815cf0976.png)

**Comment by mercury501** [comment]
Here you go @Polymega, italian:


> Downloads the enhancement packages to a temporary Windows AppData folder for project installation.

Scarica il pacchetto di migliorie in una cartella temporanea in AppData di Windows per l'installazione del progetto. 


> Feature unavailable. Cannot contact server. Please try again later.

Opzione non disponibile. Impossibile contattare il server. Si prega di riprovare più tardi.

> Error: Checksum mismatch`%n%n`File '`%1`' is corrupted.`%n%n`Do you wish to skip the installation of this component and move to the next one?`%n%n`NOTE: You can try installing this component again after the installation has been completed by opening the Setup Tool (SH2EEsetup.exe) in the game's folder, and choosing "Install or Repair Packages". It is strongly recommended you do so in order to fully experience Silent Hill 2: Enhanced Edition.

Errore: Il checksum non corrisponde %n%n Il file `%1` è corrotto. %n%n Vorresti saltare l'installazione di questo modulo e continuare col prossimo? %n%n NOTA: Puoi riprovare ad installare questo modulo di nuovo dopo il completamento dell'installazione riaprendo il Setup Tool (SH2EEsetup.exe) che si trova nella cartella del gioco, e selezionando "Installa o Ripara Pacchetti". E' caldamente consigliato di farlo, per godersi al meglio Silent Hill 2: Enhanced Edition.


> Error: Checksum mismatch`%n%n` File '`%1`' is corrupted.`%n%n`The installation of this component will be skipped. Please try again, and if the issue persists, report it to the developers.

Errore: Il checksum non corrisponde %n%n Il file `%1` è corrotto. %n%nL'installazione di questo modulo verrà saltata. Si prega di riprovare e, se il problema persiste, di contattare gli sviluppatori.

Cheers!

**Comment by lulullabydreams** [comment]
Here you go @Polymega, Japanese:

> Downloads the enhancement packages to a temporary Windows AppData folder for project installation.

プロジェクトのインストール用に、拡張パッケージをWindowsのAppData内のTempフォルダにダウンロードします。

> Feature unavailable. Cannot contact server. Please try again later.

この機能を使うことができません。サーバーに接続できないため、しばらく待ってから再度お試しください。

> Error: Checksum mismatch`%n%n`File `'%1'` is corrupted.`%n%n`Do you wish to skip the installation of this component and move to the next one`?%n%n`NOTE: You can try installing this component again after the installation has been completed by opening the Setup Tool (SH2EEsetup.exe) in the game's folder, and choosing "Install or Repair Packages". It is strongly recommended you do so in order to fully experience Silent Hill 2: Enhanced Edition.

エラー: チェックサムの不一致`%n%n`ファイル`'%1'`が破損しています。`n%n` このコンポーネントのインストールをスキップして、次のコンポーネントに移動しますか？`%n%n` 注意：インストール完了後、ゲームフォルダ内のセットアップツール（SH2EEsetup.exe）を開いて、「パッケージのインストールまたは修復」を選択すると、このコンポーネントを再インストールできます。『サイレントヒル2：エンハンスド・エディション』を十分にお楽しみいただくために、この作業を行うことを強くお勧めします。

I hope this helps!

**Comment by Polymega** [comment]
You are wonderful, @lullulabydreams! Thank you very much!! We will have these new translations added in soon. We really appreciate your help with this. 😊
