### ISSUE TITLE
Erros de caracteres na Setup Tool, após Hotfix

### ISSUE THREAD

**Issue by lucazandrade** [nipkownix/SH2EE-web-installer#28]
Olá, bom, o John me disse que você é brasileiro, então acho melhor se comunicar no nosso idioma nativo mesmo. Eu fiz uma série de correções para os textos da ferramenta de instalação, como você bem sabe. Eu usei, obviamente, o arquivo já com os textos em português que o John me "linkou" aqui no Git para editar. Então, notei algumas coisas relacionadas (que acredito eu) que estejam ligadas aos caracteres especiais de nosso idioma. Então, resolvi segui-los, mas após o hotfix do projeto, baixei novamente a ferramenta para a instalação do projeto e me deparei com isso:
![error](https://user-images.githubusercontent.com/32915382/230960675-07fae84c-da80-412f-b3ba-1b5f53636d8f.png)

**Comment by Polymega** [comment]
@nipkownix 
How have you been? I hope things are going awesome for you!!

In addition to Lucaz's request above, I've also submitted a PR to fix the tool from accidentally deleting the credits FMV: https://github.com/nipkownix/SH2EE-web-installer/pull/29

Would you have time in the near future to help with these two items?

Thanks!

**Comment by nipkownix** [comment]
@lucazandrade Seems like ``BrazilianPortuguese.iss``' encoding was messed up somehow. I'll push a fix soon.

@Polymega I've just merged the fix. Thanks!
