### ISSUE TITLE
Italian Translation for the Installer

### ISSUE THREAD

**Issue by Polymega** [nipkownix/SH2EE-web-installer#9]
@Badore90 @Bruno3589
Would either of you gents have any interest in providing an Italian translation of the Setup Tool (installer) for the Enhanced Edition project? If so, these would be the files you'd need to download and translate:

- https://github.com/nipkownix/SH2EE-web-installer/blob/master/languages/English.iss
- https://github.com/nipkownix/SH2EE-web-installer/blob/master/languages/English-license.rtf

You'd need to pay special attention to how these files are formatted and any unique code contained _within_ text strings, but it should be a similar experience to how you two improved the Italian language for the game.

Please think it over and let us know!
Thanks

**Comment by Bruno3589** [comment]
Hi @Polymega,
actually I was already considering to translate both the setup and the configuration tool, I just couldn't find the right time to do it.
I can surely start looking at the files needing translation, I'll also ask @Badore90 if he has time to help me.

As for the formatting I'll be careful but since these are formats I know (I did a bit of InnoSetup scripting at work) it shouldn't be an issue for me.

I have a question though, instead of downloading the files wouldn't it be better for you if I fork the repo, add the translation and then do a pull request? It's probably way too complicated for just two translation files, but maybe it's easier for you to track?

**Comment by Polymega** [comment]
Awesome! Thanks for your help here!

> wouldn't it be better for you if I fork the repo, add the translation and then do a pull request?

Absolutely! Whatever is easiest for you. :) Here is the Config File for translation as well:
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config.xml

For that file, please submit it to Elisha as "config_it.xml". Thank you again!

PS - For the Config Tool, as you are translating it, if you have the file named "config.xml" and place it in the same directory as the Config Tool, you should see your translation efforts take effect each time you launch the tool.

**Comment by Bruno3589** [comment]
Ok, thanks for the suggestion.
I forked the project and created a first draft of the Italian.iss language file, @Badore90 if you have time to check the file for typos and/or grammar mistakes you can download it here:
https://github.com/Bruno3589/SH2EE-web-installer/blob/italian-translation/languages/Italian.iss

I'll upload Italian-license.rtf as soon as I'm done translating it.

**Comment by Bruno3589** [comment]
BTW Labels for strings 38 and 39 are "IstallModeTitle" and "IstallModeDesc", shouldn't it be "Install" instead of "Istall"?

**Comment by Polymega** [comment]
> BTW Labels for strings 38 and 39 are "IstallModeTitle" and "IstallModeDesc", shouldn't it be "Install" instead of "Istall"?

Looks to be a little typo. But thank you for helping with the Italian translation.

@nipkownix 
I unfortunately haven't heard back from my German friend so I don't think a German translation will be coming in the immediate future.

**Comment by nipkownix** [comment]
@Bruno3589 Thank you for the contributions so far!

@Polymega No worries.

**Comment by Polymega** [comment]
Hi guys,

A new line to add to the Italian language file:
https://github.com/nipkownix/SH2EE-web-installer/commit/62b3018fc5d28b585194f9471ac0f85c70a19875#diff-6e56001e33bc6affecacdc4295020860cd2d9bf63bc3787421fd81e18ed0516a

Thank you!

**Comment by Bruno3589** [comment]
Updated: 580fc9947a22b72671c19ee93a38e5f7115f60b1

Question: is it OK to use single quote ' for apostrophes or should I use an alternative to avoid issues?

**Comment by nipkownix** [comment]
Thanks!

>Question: is it OK to use single quote ' for apostrophes or should I use an alternative to avoid issues?

Should be fine, but I'll check and let you know.
Sorry for the delay, by the way.

I assume I can manually merge the new translation? That would make it easier for someone to edit and create a PR to change anything if they wanted.

**Comment by Bruno3589** [comment]
Hi, no problem for the delay, I assumed you were on vacation.

I was waiting for @Badore90 to review the translation but I haven't heard from him, maybe it's a busy period. So I guess the translation can be merged and then fixed later if needed.

I created pull request #13, everything _should_ be ok but I'm not very familiar with the procedure so you may want to check twice.
Thanks :+1:

**Comment by Bruno3589** [comment]
Also added another update reflecting changes in 0a91dfaedcb2ba95d71c210383f21520c740d3c8
